
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycmfluvtqrwuaxjhzhxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljbWZsdXZ0cXJ3dWF4amh6aHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODk1MTMsImV4cCI6MjA2Mjc2NTUxM30.6ZhAMFQQHylpwCkpyR_Bk5HTFUTNwCZSCzLQrWaEHAA";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Importante para OAuth (login do Google)
      flowType: 'implicit' // Usar fluxo implícito para OAuth
    },
    global: {
      // Melhorias de desempenho para produção
      headers: {
        'X-App-Version': '1.0.0'
      }
    },
    realtime: {
      // Configurações para melhorar a experiência em tempo real
      reconnectAttempts: 5,
      timeout: 60000 // 60 segundos
    }
  }
);
